import 'dart:io';

import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:houmi/core/_core.dart';
import 'package:houmi/core/bases/enums/theme_type.dart';
import 'package:houmi/core/theme/_theme.dart';
import 'package:houmi/features/authentication/data/datasources/_datasources.dart';
import 'package:houmi/features/authentication/data/models/_models.dart';
import 'package:houmi/features/authentication/data/repositories/_repositories.dart';
import 'package:houmi/features/authentication/domain/repositories/_repositories.dart';
import 'package:houmi/features/authentication/presentation/pages/_pages.dart';
import 'package:houmi/features/authentication/presentation/states/_states.dart';
import 'package:houmi/features/news/presentation/states/_states.dart';
import 'package:houmi/features/notification/presentation/pages/_pages.dart';
import 'package:houmi/features/notification/presentation/states/_states.dart';
import 'package:houmi/main_page.dart';
import 'package:houmi/services/_services.dart';
import 'package:image/image.dart' as im;
import 'package:image_cropper/image_cropper.dart';
import 'package:image_picker/image_picker.dart';
import 'package:logger/logger.dart';
import 'package:path_provider/path_provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:states_rebuilder/states_rebuilder.dart';

part 'cleaner.dart';
part 'file_picker_state.dart';
part 'future_state.dart';
part 'global_state.dart';
part 'initializer.dart';
part 'navigation_state.dart';
part 'profile_state.dart';
part 'storage_state.dart';
part 'theme_state.dart';
